objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Body_shape__c</fullName>
        <label>Body shape</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ectomorph</fullName>
                </value>
                <value>
                    <fullName>Mezomorph</fullName>
                </value>
                <value>
                    <fullName>Endomorph</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Carbs__c</fullName>
        <label>Carbs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Daily_Activity__c</fullName>
        <label>Daily Activity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Small</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Daily_Carbs__c</fullName>
        <formula>IF(
    ((Daily_Protein__c * 4 + Daily_Fat__c * 9 ) &lt; Kcal__c), 
    ((Kcal__c - (Daily_Protein__c * 4 + Daily_Fat__c * 9 )) / 4),
    0
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Daily Carbs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Daily_Fat__c</fullName>
        <formula>Fat__c *  Weight__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Daily Fat</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Daily_Protein__c</fullName>
        <formula>Protein__c *  Weight__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Daily Protein</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Diet_goal__c</fullName>
        <label>Diet goal</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Reduction</fullName>
                </value>
                <value>
                    <fullName>Gain</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Expected_Weight__c</fullName>
        <label>Expected Weight</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Fat__c</fullName>
        <label>Fat</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Goal_Kcal_Diff__c</fullName>
        <label>Goal Kcal Diff</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Height__c</fullName>
        <label>Height</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Kcal__c</fullName>
        <description>expected kcal intake</description>
        <label>Kcal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Manual_Calculation__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Not recommended (advance users only)</inlineHelpText>
        <label>Manual Calculation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Protein__c</fullName>
        <label>Protein</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sex__c</fullName>
        <label>Sex</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/FitAppMainService.cls
/*------------------------------------------------------------
Author:        Cezary Zeleznicki
Company:
Description:   FitAppMainService
History
<Date>      <Authors Name>     <Brief Description of Change>
04.10.2018  Cezary Zeleznicki       creation
------------------------------------------------------------*/

public class FitAppMainService extends BaseComponent{

    public ContactWrapper getContact() {
        ContactWrapper cw;

        List<Contact> contacts = [
            SELECT Id, FirstName, LastName, Birthdate, Age__c, Body_shape__c, Carbs__c, Daily_Activity__c,
                Diet_goal__c, Expected_Weight__c, Fat__c, Height__c, Kcal__c, Manual_Calculation__c,
                Protein__c, Sex__c, Weight__c, Goal_Kcal_Diff__c, Daily_Protein__c, Daily_Carbs__c, Daily_Fat__c,
                (SELECT Id, Duration__c, Intensitivity__c, Quantity__c, Type__c FROM Trainings__r)
            FROM Contact
            WHERE Id IN (SELECT ContactId FROM User WHERE Id = :UserInfo.getUserId())
        ];

        if(!contacts.isEmpty()) {
            cw = new ContactWrapper(contacts[0]);
            cw.picklists = loadPicklists();
        }

        return cw;
    }

    public void saveContact(ContactWrapper contact) {

        upsert contact.record;

        if(contact.trainings != null && !contact.trainings.isEmpty()) {
            saveTrainings(contact.trainings);
        }
    }

    private void saveTrainings(List<Training__c> trainings) {
        upsert trainings;
    }

    private ContactPicklists loadPicklists() {
        ContactPicklists picklists = new ContactPicklists();

        picklists.sex = getPicklistValues(Contact.class.toString(), 'Sex__c');
        picklists.dailyActivity = getPicklistValues(Contact.class.toString(), 'Daily_Activity__c');
        picklists.dietGoal = getPicklistValues(Contact.class.toString(), 'Diet_goal__c');
        picklists.bodyShape = getPicklistValues(Contact.class.toString(), 'Body_shape__c');
        picklists.intensivity = getPicklistValues(Training__c.class.toString(), 'Intensitivity__c');
        picklists.trainingType = getPicklistValues(Training__c.class.toString(), 'Type__c');

        return picklists;
    }

    public class ContactWrapper {
        @AuraEnabled
        public Contact record;
        @AuraEnabled
        public List<Training__c> trainings;
        @AuraEnabled
        public Boolean isSetupCompleted;
        @AuraEnabled
        public ContactPicklists picklists;

        public ContactWrapper(Contact record) {
            this.record = record;
            this.isSetupCompleted = record.Age__c != null && record.Body_shape__c != null && record.Carbs__c != null &&
                record.Daily_Activity__c != null && record.Diet_goal__c != null && record.Fat__c != null &&
                record.Height__c != null && record.Kcal__c != null && record.Protein__c != null &&
                record.Manual_Calculation__c != null && record.Sex__c != null && record.Weight__c != null;
        }
    }

    public class ContactPicklists {
        @AuraEnabled
        public List<PicklistValue> sex;
        @AuraEnabled
        public List<PicklistValue> dailyActivity;
        @AuraEnabled
        public List<PicklistValue> dietGoal;
        @AuraEnabled
        public List<PicklistValue> bodyShape;
        @AuraEnabled
        public List<PicklistValue> intensivity;
        @AuraEnabled
        public List<PicklistValue> trainingType;
    }
}