objects/Meal__c.object
<CustomObject>
    <fields>
        <fullName>Carbs__c</fullName>
        <label>Carbs</label>
        <summarizedField>MealProduct__c.Carbs__c</summarizedField>
        <summaryForeignKey>MealProduct__c.Meal__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Fat__c</fullName>
        <label>Fat</label>
        <summarizedField>MealProduct__c.Fat__c</summarizedField>
        <summaryForeignKey>MealProduct__c.Meal__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Kcal__c</fullName>
        <description>kcal per gramm</description>
        <label>Kcal</label>
        <summarizedField>MealProduct__c.Kcal__c</summarizedField>
        <summaryForeignKey>MealProduct__c.Meal__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Protein__c</fullName>
        <label>Protein</label>
        <summarizedField>MealProduct__c.Protein__c</summarizedField>
        <summaryForeignKey>MealProduct__c.Meal__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Meal</label>
    <nameField>
        <label>Meal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MealPlanMeal__c.object
<CustomObject>
    <description>junction</description>
    <fields>
        <fullName>Meal__c</fullName>
        <label>Meal</label>
        <referenceTo>Meal__c</referenceTo>
        <relationshipLabel>MealPlanMeals</relationshipLabel>
        <relationshipName>MealPlanMeals</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>MealPlanMeal</label>
    <nameField>
        <displayFormat>MPM-{0000000000}</displayFormat>
        <label>MealPlanMeal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MealPlanMeals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/MealPlanMealTriggerHelper.cls
/*------------------------------------------------------------
Author:        Cezary Zeleznicki
Company:
Description:   MealPlanMealHelper
History
<Date>      <Authors Name>     <Brief Description of Change>
08/12/2018  Cezary Zeleznicki       creation
------------------------------------------------------------*/

public class MealPlanMealTriggerHelper implements ITrigger{

    public void beforeInsert(List<MealPlanMeal__c> newMealPlanMeals) {
        populateAllMacroElements(newMealPlanMeals);
    }

    public void afterInsert(List<MealPlanMeal__c> newMealPlanMeals){}

    public void beforeUpdate(List<MealPlanMeal__c> newMealPlanMeals, List<MealPlanMeal__c> oldMealPlanMeals){
        populateAllMacroElements(newMealPlanMeals);
    }

    public void afterUpdate(List<MealPlanMeal__c> newMealPlanMeals, List<MealPlanMeal__c> oldMealPlanMeals){}

    private void populateAllMacroElements(List<MealPlanMeal__c> newMealPlanMeals) {
        Map<Id, Meal__c> id2Meal = getAllMeals(newMealPlanMeals);

        for(MealPlanMeal__c mpm : newMealPlanMeals) {
            if(!id2Meal.containsKey(mpm.Meal__c)) {
                continue;
            }

            Meal__c meal = id2Meal.get(mpm.Meal__c);

            mpm.Protein__c = meal.Protein__c;
            mpm.Carbs__c = meal.Carbs__c;
            mpm.Fat__c = meal.Fat__c;
            mpm.Kcal__c = meal.Kcal__c;
        }
    }

    private Map<Id, Meal__c> getAllMeals(List<MealPlanMeal__c> newMealPlanMeals) {
        Set<Id> mealIds = new Set<Id>();

        for(MealPlanMeal__c mp : newMealPlanMeals) {
            mealIds.add(mp.Meal__c);
        }

        Map<Id, Meal__c> id2Meal = new Map<Id, Meal__c>([SELECT Id, Protein__c, Carbs__c, Fat__c, Kcal__c FROM Meal__c WHERE Id IN :mealIds]);

        return id2Meal;
    }
}